### PR TITLE
Add Sequential Predictive Conformal Inference (SPCI) method for Time Series

### LINKED ISSUE #370: Sequential Predictive Conformal Inference (SCPI) for Time Series
**Describe the solution you'd like**
Include `SCPI` as a second, alternative method within the `MapieTimeSeriesRegressor` class alongside the existing `EnbPI` method.

**Why is this beneficial?**
SCPI improves upon EnbPI by including serial dependence across prediction residuals (or conformity score), aka _sequential_ conformal prediction. This can further reduce the prediction interval width for the same data and empirical coverage compared to EnbPI.

**Additional context**
Xu, C. and Xie, Y. Sequential predictive conformal inference for time series. arXiv preprint
arXiv:2212.03463, 2022b. [[link](https://arxiv.org/abs/2212.03463)]

### PR DESCRIPTION
**Pull request by Kevin-Chen0**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #370

## Type of change

Please remove options that are irrelevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] I have read the [contributing guidelines](https://github.com/simai-ml/MAPIE/blob/master/CONTRIBUTING.rst)
- [ ] I have updated the [HISTORY.rst](https://github.com/simai-ml/MAPIE/blob/master/HISTORY.rst) and [AUTHORS.rst](https://github.com/simai-ml/MAPIE/blob/master/AUTHORS.rst) files
- [ ] Linting passes successfully : `make lint`
- [ ] Typing passes successfully : `make type-check`
- [ ] Unit tests pass successfully : `make tests`
- [ ] Coverage is 100% : `make coverage`
- [ ] Documentation builds successfully : `make doc`

### CODE REVIEW

**Comment by LacombeLouis** [comment]
Hey @Kevin-Chen0,
Note that I would fork from the following branch: [334-adaptive-conformal-predictions-for-time-series](https://github.com/scikit-learn-contrib/MAPIE/tree/334-adaptive-conformal-predictions-for-time-series).

**Comment by Kevin-Chen0** [comment]
> Hey @Kevin-Chen0, Note that I would fork from the following branch: [334-adaptive-conformal-predictions-for-time-series](https://github.com/scikit-learn-contrib/MAPIE/tree/334-adaptive-conformal-predictions-for-time-series). Looking forward to see your PR!

Hi @LacombeLouis I have just merged the latest `scikit-learn-contrib:334-adaptive-conformal-predictions-for-time-series` branch into `Tempor-ai:370-sequential-predictive-conformal-inference-for-time-series`. So SCPI will adhere to the ACI structure. Please lmk if you see anything else. Thx!

**Comment by Kevin-Chen0** [comment]
Hi @thibaultcordier, my friend @grgstock will tackle this SPCI PR moving forward. What is the best way for him to reach out to you and your team in case he has specific questions about the existing MAPIE code base?

**Comment by thibaultcordier** [comment]
> Hi @thibaultcordier, my friend @grgstock will tackle this SPCI PR moving forward. What is the best way for him to reach out to you and your team in case he has specific questions about the existing MAPIE code base?

Hi @Kevin-Chen0, @grgstock, the best way for him to contact our team is to contact us directly via email [(see the AUTHORS.rst file)](https://github.com/scikit-learn-contrib/MAPIE/blob/master/AUTHORS.rst) and in PR conversation. We will take the time to definitively integrate your PR into the MAPIE code by agreeing on the structure of the code to keep.

**Comment by Valentin-Laurent** [comment]
@Kevin-Chen0 @grgstock long time no speak
We closed this as the PR seemed stalled.
If by any chance you still want to work on that, feel free to re-open it anytime

**Pull request closed without merging**
