### PR TITLE
Fixes #495 : Correct EnbPI Prediction Intervals centering

### LINKED ISSUE #495: EnbPI Prediction Intervals not centered correctly
Hello MAPIE team, 

Congratulations on your excellent work! I have identified an error in the computation of the prediction intervals generated by EnbPI in MAPIE.

**Describe the bug**

The prediction intervals generated by the EnbPI method in MAPIE do not align with the expected behavior described in the pseudo code provided in the original paper.

**Expected behavior**

The prediction intervals should be centered at:
\[ 
f^{\Phi}_t(x_t) = \Phi \left(f^{\Phi}_i(x_t), i = 1, \ldots, T \right)
\]
Expected Centering

However, in the `predict` function of the `EnsembleRegressor` class, where the interval bounds are initialized, the bounds are set with the out-of-fold (oof) prediction of a single estimator rather than the aggregation of `y_pred_multi` as indicated in the pseudocode. This issue is highlighted in the following screenshot:

Incorrect Initialization

**Suggested Solution**

A simple solution would be to replace this part with something like the following:

Suggested Solution

Thank you for your attention to this matter!

### PR DESCRIPTION
**Pull request by jawharmohammed**
# Description

**Addresses the issue #495 concerning the prediction intervals generated by EnbPI.**

The intervals are now centered at the aggregation of `y_pred_multi` instead of the prediction of a single estimator, aligning with the pseudocode.

Fixes #495 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist

- [x] I have read the [contributing guidelines](https://github.com/scikit-learn-contrib/MAPIE/blob/master/CONTRIBUTING.rst)
- [x] I have updated the [HISTORY.rst](https://github.com/scikit-learn-contrib/MAPIE/blob/master/HISTORY.rst) and [AUTHORS.rst](https://github.com/scikit-learn-contrib/MAPIE/blob/master/AUTHORS.rst) files
- [x] Linting passes successfully : `make lint`
- [x] Typing passes successfully : `make type-check`
- [x] Unit tests pass successfully : `make tests`
- [x] Coverage is 100% : `make coverage`
- [x] Documentation builds successfully : `make doc`

### CODE REVIEW

**Comment by vincentblot28** [comment]
hi @jawharmohammed,

Thank you very much for this fix, this is great ! 

To improve the readability of the code, maybe you could do as following:

```python
elif self.method == "plus":
    y_pred_multi_low = y_pred_multi
    y_pred_multi_up = y_pred_multi
elif self.method == "enbpi":
    y_pred_aggregate = aggregate_all(self.agg_function, y_pred_multi)
    y_pred_multi_low = y_pred_aggregate[:, np.newaxis]
    y_pred_multi_up = y_pred_aggregate[:, np.newaxis]
else:
    y_pred_multi_low = y_pred[:, np.newaxis]
    y_pred_multi_up = y_pred[:, np.newaxis]

if ensemble:
    y_pred = aggregate_all(self.agg_function, y_pred_multi)
```

This way, even if we compute the aggregated prediction twice, the code will be easier to understand :) 

Now as the intervals are slightly modified, some tests return errors, but you are almost there !

Again, thank you for this fix

Vincent

**Comment by Valentin-Laurent** [comment]
Hello @jawharmohammed, thank you very much for your work.
It seems that some tests are failing (namely, the linting phase, and some tests on intervals). Regarding intervals, you can modify them directly in the tests: it is normal that they change given that you corrected how they are computed.
Let us know if you need more guidance.
cc @vincentblot28

**Comment by jawharmohammed** [comment]
Hello @Valentin-Laurent

Thank you for your guidance!

Apologies for the delay. Yes, indeed, I corrected some tests on intervals, and it worked. Let me know if something else should be changed.

Mohammed

**Review by Valentin-Laurent — APPROVED** [review]

**Comment by Valentin-Laurent** [comment]
Hello @jawharmohammed, all good, thank you for your contribution!

**Pull request merged**
